#define AppName "DeskCanvas"
#define AppVersion "1.2.0-beta.13"
#define AppFileVersion "1.2.0.13"
#define AppExeName "DeskCanvas.exe"
#define PayloadPath "..\artifacts\beta\DeskCanvas-1.2.0-beta.13-win-x64\DeskCanvas.exe"
#include "DeskCanvas.v31.Beta4.CodexUsage.SingleFile.iss"
